<!DOCTYPE html>
<html>
<head>
    <style>
        /* Add professional styling */
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .company-logo {
            max-width: 200px;
            margin-bottom: 10px;
        }
        .report-title {
            font-size: 24px;
            font-weight: bold;
            color: #2c3e50;
            margin-bottom: 5px;
        }
        .report-meta {
            font-size: 12px;
            color: #666;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
        }
        .summary-section {
            margin-top: 20px;
            padding: 15px;
            background-color: #f8f9fa;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #666;
            padding: 10px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        @if($company_details['logo'] ?? false)
            <img src="{{ $company_details['logo'] }}" class="company-logo">
        @endif
        <h1 class="report-title">Loan Report</h1>
        <div class="report-meta">
            Period: {{ $startDate->format('M d, Y') }} - {{ $endDate->format('M d, Y') }}<br>
            Generated on: {{ $generated_at->format('M d, Y H:i:s') }}<br>
            Generated by: {{ $generated_by }}
        </div>
    </div>

    <div class="summary-section">
        <h3>Summary</h3>
        <p>Total Loans: {{ $summary['total_loans'] }}</p>
        <p>Total Amount: {{ number_format($totalAmount, 2) }}</p>
        <p>Average Loan Amount: {{ number_format($summary['average_amount'], 2) }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Employee</th>
                <th>Department</th>
                <th>Date</th>
                <th>SSS Loan</th>
                <th>Pagibig Loan</th>
                <th>Cash Advance</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($loans as $loan)
                <tr>
                    <td>{{ $loan->employee->full_name }}</td>
                    <td>{{ $loan->employee->department->name }}</td>
                    <td>{{ $loan->date->format('M d, Y') }}</td>
                    <td>{{ number_format($loan->sss_loan, 2) }}</td>
                    <td>{{ number_format($loan->pagibig_loan, 2) }}</td>
                    <td>{{ number_format($loan->cash_advance, 2) }}</td>
                    <td>{{ number_format($loan->sss_loan + $loan->pagibig_loan + $loan->cash_advance, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        {{ $company_details['name'] }} | {{ $company_details['address'] }} | {{ $company_details['contact'] }}
        <br>
        Page 1 of 1
    </div>
</body>
</html>
